import os

actors = [
    "MetalHub (System/Platform) [Source: Architecture Consolidation]",
    "Invisible Advisor (System Actor) [Source: Architecture Consolidation]",
    "Silent Mentor (System Actor) [Source: Architecture Consolidation]",
    "Trusted Companion (System Actor) [Source: Architecture Consolidation]",
    "User / کاربر (Human Actor) [Source: Architecture Consolidation]",
    "Manager / مدیر (Human Actor) [Source: Architecture Consolidation]",
    "Enterprise Architect / معمار Enterprise (Human Actor) [Source: Architecture Consolidation]",
    "Architecture Review Board / هیئت معماری مستقل (Human Actor/Group) [Source: Architecture Consolidation]",
    "Company / شرکت (Organization Actor) [Source: Architecture Consolidation]",
    "Structural Engineer (مهندس سازه) [Source: Volume V, Chapter 3]",
    "Procurement Expert (کارشناس خرید) [Source: Volume V, Chapter 3]",
    "QC Manager (مسئول کنترل کیفیت) [Source: Volume V, Chapter 3]",
    "Project Manager (مدیر پروژه) [Source: Volume V, Chapter 3]",
    "Procurement Manager [Source: Volume V, Chapter 6]",
    "Lead Engineer [Source: Volume V, Chapter 6]",
    "Project Manager [Source: Volume V, Chapter 6]",
    "Customer [Source: Volume V, Chapter 6]",
    "Decision Review Board [Source: Volume V, Chapter 6]",
    "Engineering Reasoning Engine [Source: Volume V, Chapter 1]",
    "Supplier Matching Engine [Source: Volume V, Chapter 1]",
    "Cost Reasoning Engine [Source: Volume V, Chapter 1]",
    "Risk Reasoning Engine [Source: Volume V, Chapter 1]",
    "Knowledge Reasoning Engine [Source: Volume V, Chapter 1]",
    "Coordination Reasoning Engine [Source: Volume V, Chapter 1]",
    "Decision Orchestrator [Source: Volume V, Chapter 3]",
    "Engineering Intelligence Agent [Source: Volume V, Chapter 3]",
    "Supply Intelligence Agent [Source: Volume V, Chapter 3]",
    "Cost Intelligence Agent [Source: Volume V, Chapter 3]",
    "Logistics Intelligence Agent [Source: Volume V, Chapter 3]",
    "Quality Intelligence Agent [Source: Volume V, Chapter 3]",
    "Risk Intelligence Agent [Source: Volume V, Chapter 3]",
    "Knowledge Intelligence Agent [Source: Volume V, Chapter 3]",
    "Compliance Intelligence Agent [Source: Volume V, Chapter 3]",
    "System (MetalHub / SideroHub / The Entity) [Source: Volume XII, Chapter 1]",
    "کاربر (User) [Source: Volume XII, Chapter 2]",
    "مشتری بزرگ (Large Customer) [Source: Volume XII, Chapter 2]",
    "عضو جدید سازمان (New Organization Member) [Source: Volume XII, Chapter 2]",
    "انسان (Human) [Source: Volume XII, Chapter 3]",
    "مدیر پروژه (Project Manager) [Source: Volume XII, Chapter 3]",
    "مشاور مورد اعتماد (Trusted Mentor) [Source: Volume XII, Chapter 3]",
    "مدیر (Manager) [Source: Volume XII, Chapter 4]",
    "سرمایه‌گذار (Investor) [Source: Volume XII, Chapter 4]",
    "مشتری (Customer) [Source: Volume XII, Chapter 4]",
    "تأمین‌کننده (Supplier) [Source: Volume XII, Chapter 4]",
    "مدیران صنعتی (Industrial Managers) [Source: Volume XII, Chapter 5]",
    "تیم (Team) [Source: Volume XII, Chapter 6]",
    "مدیران جوان (Young Managers) [Source: Volume XII, Chapter 6]",
    "بنیان‌گذاران (Founders) [Source: Volume XII, Chapter 6]",
    "نسل جدید / نسل بعد (Next Generation) [Source: Volume XII, Chapter 7]",
    "امین اکوسیستم (Ecosystem Steward) [Source: Volume XII, Chapter 7]",
    "اکوسیستم (Ecosystem) [Source: Volume XII, Chapter 8]",
    "کارفرما (Client) [Source: Volume II, Chapter 1]",
    "مدیر خرید (Procurement Manager) [Source: Volume II, Chapter 1]",
    "مدیر پروژه مشتری [Source: Volume II, Chapter 1]",
    "مشاور [Source: Volume II, Chapter 1]",
    "شرکت مهندسین مشاور [Source: Volume II, Chapter 1]",
    "معمار [Source: Volume II, Chapter 1]",
    "طراح صنعتی [Source: Volume II, Chapter 1]",
    "مهندس طراحی [Source: Volume II, Chapter 1]",
    "مهندس محاسب [Source: Volume II, Chapter 1]",
    "مهندس ساخت [Source: Volume II, Chapter 1]",
    "فروشنده مواد اولیه [Source: Volume II, Chapter 1]",
    "انباردار [Source: Volume II, Chapter 1]",
    "مرکز برش لیزر [Source: Volume II, Chapter 1]",
    "مرکز برش پلاسما [Source: Volume II, Chapter 1]",
    "خمکاری [Source: Volume II, Chapter 1]",
    "تراشکاری [Source: Volume II, Chapter 1]",
    "فرزکاری [Source: Volume II, Chapter 1]",
    "ماشین‌کاری CNC [Source: Volume II, Chapter 1]",
    "جوشکاری [Source: Volume II, Chapter 1]",
    "رنگ [Source: Volume II, Chapter 1]",
    "گالوانیزه [Source: Volume II, Chapter 1]",
    "مونتاژ [Source: Volume II, Chapter 1]",
    "سازنده استراکچر [Source: Volume II, Chapter 1]",
    "آزمایشگاه [Source: Volume II, Chapter 1]",
    "بازرس [Source: Volume II, Chapter 1]",
    "کنترل کیفیت [Source: Volume II, Chapter 1]",
    "حمل‌ونقل [Source: Volume II, Chapter 1]",
    "بیمه [Source: Volume II, Chapter 1]",
    "خدمات گمرکی [Source: Volume II, Chapter 1]",
    "آزمایشگاه‌های مستقل [Source: Volume II, Chapter 1]",
    "شرکت‌های بازرسی [Source: Volume II, Chapter 1]",
    "بانک [Source: Volume II, Chapter 1]",
    "پرداخت [Source: Volume II, Chapter 1]",
    "امضای دیجیتال [Source: Volume II, Chapter 1]",
    "ارائه‌دهندگان خدمات ابری [Source: Volume II, Chapter 1]",
    "سیستم‌های CAD/CAM [Source: Volume II, Chapter 1]",
    "سیستم‌های ERP [Source: Volume II, Chapter 1]",
    "سیستم‌های PLM [Source: Volume II, Chapter 1]",
    "Buyer [Source: Volume II, Chapter 2]",
    "Manufacturer [Source: Volume II, Chapter 2]",
    "Supplier [Source: Volume II, Chapter 2]",
    "Inspection Company [Source: Volume II, Chapter 2]",
    "Logistics Company [Source: Volume II, Chapter 2]",
    "Engineering Office [Source: Volume II, Chapter 2]",
    "Insurance Company [Source: Volume II, Chapter 2]",
    "MetalHub [Source: Volume II, Chapter 2]",
    "مهندس [Source: Volume II, Chapter 2]",
    "مدیر خرید [Source: Volume II, Chapter 2]",
    "مدیر پروژه [Source: Volume II, Chapter 2]",
    "بازرس [Source: Volume II, Chapter 2]",
    "اپراتور [Source: Volume II, Chapter 2]",
    "مدیر کارخانه [Source: Volume II, Chapter 2]",
    "Operator [Source: Volume II, Chapter 3]",
    "AI Agents [Source: Volume II, Chapter 7]",
    "Recommendation Engine [Source: Volume II, Chapter 7]",
    "Risk Engine [Source: Volume II, Chapter 7]",
]

domain_objects = [
    "Digital Case [Source: Architecture Consolidation]",
    "Industrial Memory [Source: Architecture Consolidation]",
    "Work DNA [Source: Architecture Consolidation]",
    "Decision Intelligence [Source: Architecture Consolidation]",
    "Decision Friction [Source: Architecture Consolidation]",
    "Professional Journey [Source: Architecture Consolidation]",
    "Defendability [Source: Architecture Consolidation]",
    "Evidence Graph [Source: Architecture Consolidation]",
    "Knowledge Curation [Source: Architecture Consolidation]",
    "Adaptive Guidance [Source: Architecture Consolidation]",
    "Trust Architecture [Source: Architecture Consolidation]",
    "Professional Confidence Loop [Source: Architecture Consolidation]",
    "Decision / تصمیم [Source: Architecture Consolidation]",
    "Evidence / شواهد [Source: Architecture Consolidation]",
    "Knowledge / دانش [Source: Architecture Consolidation]",
    "Supply Chain / زنجیره تأمین [Source: Architecture Consolidation]",
    "Requirement [Source: Volume V, Chapter 2]",
    "Engineering Objects [Source: Volume V, Chapter 2]",
    "Capability Objects [Source: Volume V, Chapter 2]",
    "Commercial Objects [Source: Volume V, Chapter 2]",
    "Execution Objects [Source: Volume V, Chapter 2]",
    "Knowledge Objects [Source: Volume V, Chapter 2]",
    "Drawings [Source: Volume V, Chapter 2]",
    "BOM [Source: Volume V, Chapter 2]",
    "RFQ [Source: Volume V, Chapter 2]",
    "Suppliers [Source: Volume V, Chapter 2]",
    "Materials [Source: Volume V, Chapter 2]",
    "Quotes [Source: Volume V, Chapter 2]",
    "Work Packages [Source: Volume V, Chapter 2]",
    "Inspection [Source: Volume V, Chapter 2]",
    "Shipment [Source: Volume V, Chapter 2]",
    "Lessons Learned [Source: Volume V, Chapter 2]",
    "Decision Card [Source: Volume V, Chapter 3]",
    "Episodic Memory [Source: Volume V, Chapter 3]",
    "Semantic Memory [Source: Volume V, Chapter 3]",
    "Procedural Memory [Source: Volume V, Chapter 3]",
    "Strategic Decisions [Source: Volume V, Chapter 4]",
    "Tactical Decisions [Source: Volume V, Chapter 4]",
    "Operational Decisions [Source: Volume V, Chapter 4]",
    "Learning Decisions [Source: Volume V, Chapter 4]",
    "Decision Graph [Source: Volume V, Chapter 4]",
    "Decision Quality Index (DQI) [Source: Volume V, Chapter 4]",
    "Data [Source: Volume V, Chapter 5]",
    "Information [Source: Volume V, Chapter 5]",
    "Evidence [Source: Volume V, Chapter 5]",
    "Evidence Chain [Source: Volume V, Chapter 5]",
    "Evidence Debt [Source: Volume V, Chapter 5]",
    "Evidence Portfolio [Source: Volume V, Chapter 5]",
    "Hypothesis [Source: Volume V, Chapter 5]",
    "Decision Feedback Loop [Source: Volume V, Chapter 7]",
    "Knowledge Confidence [Source: Volume V, Chapter 7]",
    "Learning Backlog [Source: Volume V, Chapter 7]",
    "Industrial Memory [Source: Volume V, Chapter 7]",
    "Industrial Maturity Index (IMI) [Source: Volume V, Chapter 7]",
    "Identity [Source: Volume XII, Chapter 1]",
    "Brand [Source: Volume XII, Chapter 1]",
    "Essence [Source: Volume XII, Chapter 1]",
    "Mission [Source: Volume XII, Chapter 1]",
    "Strategy [Source: Volume XII, Chapter 1]",
    "Technology [Source: Volume XII, Chapter 1]",
    "Expression [Source: Volume XII, Chapter 1]",
    "Trust [Source: Volume XII, Chapter 1]",
    "Knowledge [Source: Volume XII, Chapter 1]",
    "Guidance [Source: Volume XII, Chapter 1]",
    "Collective Learning [Source: Volume XII, Chapter 1]",
    "Decision Quality [Source: Volume XII, Chapter 1]",
    "Institutional Memory [Source: Volume XII, Chapter 1]",
    "Ecosystem Intelligence [Source: Volume XII, Chapter 1]",
    "Wisdom [Source: Volume XII, Chapter 1]",
    "Responsibility [Source: Volume XII, Chapter 1]",
    "Continuity [Source: Volume XII, Chapter 1]",
    "IAD (Identity Architecture Decision) [Source: Volume XII, Chapter 1]",
    "Identity Mirror [Source: Volume XII, Chapter 2]",
    "Identity Compass [Source: Volume XII, Chapter 2]",
    "IAF (Identity Discovery Framework) [Source: Volume XII, Chapter 2]",
    "Workflow [Source: Volume XII, Chapter 2]",
    "ADR (Architecture Decision Record) [Source: Volume XII, Chapter 2]",
    "Character [Source: Volume XII, Chapter 3]",
    "Mentor Interaction Model [Source: Volume XII, Chapter 3]",
    "Calm Intelligence [Source: Volume XII, Chapter 3]",
    "Character Consistency [Source: Volume XII, Chapter 3]",
    "Email [Source: Volume XII, Chapter 3]",
    "Notification [Source: Volume XII, Chapter 3]",
    "Dashboard [Source: Volume XII, Chapter 3]",
    "قرارداد (Contract) [Source: Volume XII, Chapter 3]",
    "گزارش (Report) [Source: Volume XII, Chapter 3]",
    "API [Source: Volume XII, Chapter 3]",
    "CAD (Character Architecture Decision) [Source: Volume XII, Chapter 3]",
    "CAF (Character Alignment Framework) [Source: Volume XII, Chapter 3]",
    "Character Principles [Source: Volume XII, Chapter 3]",
    "Calm Intelligence Guidelines [Source: Volume XII, Chapter 3]",
    "Character Review Checklist [Source: Volume XII, Chapter 3]",
    "Conscience [Source: Volume XII, Chapter 4]",
    "Ethical Memory [Source: Volume XII, Chapter 4]",
    "ECF (Ethical Conscience Framework) [Source: Volume XII, Chapter 4]",
    "Growth Signature [Source: Volume XII, Chapter 5]",
    "Silent Education [Source: Volume XII, Chapter 5]",
    "Confidence Curve [Source: Volume XII, Chapter 5]",
    "HTF (Human Transformation Framework) [Source: Volume XII, Chapter 5]",
    "Purpose [Source: Volume XII, Chapter 6]",
    "Vision [Source: Volume XII, Chapter 6]",
    "PPF (Purpose Preservation Framework) [Source: Volume XII, Chapter 6]",
    "Long Horizon Principle [Source: Volume XII, Chapter 6]",
    "Legacy [Source: Volume XII, Chapter 7]",
    "Stewardship [Source: Volume XII, Chapter 7]",
    "LEF (Legacy Evolution Framework) [Source: Volume XII, Chapter 7]",
    "Name [Source: Volume XII, Chapter 8]",
    "NDF (Name Discovery Framework) [Source: Volume XII, Chapter 8]",
    "Name Evaluation Matrix [Source: Volume XII, Chapter 8]",
    "Identity Compression Criteria [Source: Volume XII, Chapter 8]",
    "Long-Term Naming Principles [Source: Volume XII, Chapter 8]",
    "Buyer [Source: Volume II, Introduction]",
    "Engineer [Source: Volume II, Introduction]",
    "RFQ [Source: Volume II, Introduction]",
    "Quotation [Source: Volume II, Introduction]",
    "Commitment [Source: Volume II, Introduction]",
    "Material [Source: Volume II, Introduction]",
    "Machine [Source: Volume II, Introduction]",
    "Supplier [Source: Volume II, Introduction]",
    "Manufacturer [Source: Volume II, Introduction]",
    "Project [Source: Volume II, Introduction]",
    "Inspection [Source: Volume II, Introduction]",
    "Evidence [Source: Volume II, Introduction]",
    "Certificate [Source: Volume II, Introduction]",
    "Shipment [Source: Volume II, Introduction]",
    "Invoice [Source: Volume II, Introduction]",
    "Decision [Source: Volume II, Introduction]",
    "Risk [Source: Volume II, Introduction]",
    "Revision [Source: Volume II, Introduction]",
    "Capability [Source: Volume II, Introduction]",
    "Production Line [Source: Volume II, Introduction]",
    "Process [Source: Volume II, Introduction]",
    "Operation [Source: Volume II, Introduction]",
    "Digital Thread [Source: Volume II, Introduction]",
    "Trust [Source: Volume II, Introduction]",
    "Need [Source: Volume II, Chapter 1]",
    "Engineering Understanding [Source: Volume II, Chapter 1]",
    "Manufacturing Strategy [Source: Volume II, Chapter 1]",
    "Supplier Selection [Source: Volume II, Chapter 1]",
    "Commercial Validation [Source: Volume II, Chapter 1]",
    "Production [Source: Volume II, Chapter 1]",
    "Logistics [Source: Volume II, Chapter 1]",
    "Delivery [Source: Volume II, Chapter 1]",
    "Knowledge [Source: Volume II, Chapter 1]",
    "Trust Capital [Source: Volume II, Chapter 1]",
    "Industrial Capability Network (ICN) [Source: Volume II, Chapter 1]",
    "Organization [Source: Volume II, Chapter 2]",
    "Person [Source: Volume II, Chapter 2]",
    "Project [Source: Volume II, Chapter 2]",
    "Requirement [Source: Volume II, Chapter 2]",
    "RFQ [Source: Volume II, Chapter 2]",
    "Capability [Source: Volume II, Chapter 2]",
    "Process [Source: Volume II, Chapter 2]",
    "Machine [Source: Volume II, Chapter 2]",
    "Material [Source: Volume II, Chapter 2]",
    "Commitment [Source: Volume II, Chapter 2]",
    "Evidence [Source: Volume II, Chapter 2]",
    "Decision [Source: Volume II, Chapter 2]",
    "Trust [Source: Volume II, Chapter 2]",
    "Currency [Source: Volume II, Chapter 2]",
    "Tax Rule [Source: Volume II, Chapter 2]",
    "Incoterm [Source: Volume II, Chapter 2]",
    "Compliance Rule [Source: Volume II, Chapter 2]",
    "Digital Signature [Source: Volume II, Chapter 2]",
    "Drawings [Source: Volume II, Chapter 3]",
    "Parts [Source: Volume II, Chapter 3]",
    "Inspections [Source: Volume II, Chapter 3]",
    "Shipments [Source: Volume II, Chapter 3]",
    "Invoices [Source: Volume II, Chapter 3]",
    "Risks [Source: Volume II, Chapter 3]",
    "Country [Source: Volume II, Chapter 3]",
    "Problem [Source: Volume II, Chapter 3]",
    "Alternatives [Source: Volume II, Chapter 3]",
    "Outcome [Source: Volume II, Chapter 3]",
    "Quality Rules [Source: Volume II, Chapter 3]",
    "Insurance [Source: Volume II, Chapter 3]",
    "State [Source: Volume II, Chapter 4]",
    "Event [Source: Volume II, Chapter 5]",
    "Metadata [Source: Volume II, Chapter 5]",
    "Ledger [Source: Volume II, Chapter 6]",
    "Knowledge Graph [Source: Volume II, Chapter 7]"
]

def write_md(file_path, items, prefix, title):
    content = f"# {title}\\n\\n"
    for i, item in enumerate(items, 1):
        content += f"- **{prefix}-{i:03d}**: {item}\\n"
    
    os.makedirs(os.path.dirname(file_path), exist_ok=True)
    with open(file_path, 'w', encoding='utf-8') as f:
        f.write(content)

write_md(r"d:\\AI-Project\\Business\\docs\\architecture\\specifications\\03-actors.md", actors, "ACT", "Actors Specification")
write_md(r"d:\\AI-Project\\Business\\docs\\architecture\\specifications\\04-domain-objects.md", domain_objects, "DOM", "Domain Objects Specification")

print("Files written successfully.")
